[package]
name = "remus8080"
version = "1.0.0"
authors = ["Skosulor"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.9"
termion = "1.5"
rand = "0.8.5"
structopt = "0.3.13"
